; PlatformIO 專案設定檔
;
;   建置選項：build flags、source filter
;   上傳選項：自訂 upload port、speed 與額外 flags
;   Library 選項：dependencies 與額外 library 儲存位置
;   進階選項：額外 scripting
;
; 其他選項與範例請參考文件
; https://docs.platformio.org/page/projectconf.html

[env:atmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_protocol = wiring
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit ST7735 and ST7789 Library
    Adafruit ImageReader Library
    Adafruit EPD
    SdFat - Adafruit Fork
    ArduinoSTL
