[platformio]
default_envs = small

[common]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
upload_protocol = stlink
upload_port = COM3
build_flags =
	-Os
	-flto
	-ffunction-sections
	-fdata-sections
	-fno-exceptions
	-DENABLE_RENDER_STATS=0
	-DENABLE_SD_BMP_ASSETS=0
	-DENABLE_SD_RLE_ASSETS=1
	-DENABLE_GUESS_GAME_SINGLE_ROUND=1
build_unflags =
	-Og
	-O0
	-O1
	-O2
	-O3
lib_deps =
	adafruit/Adafruit GFX Library @ ^1.11.5
	adafruit/Adafruit ST7735 and ST7789 Library
	adafruit/SdFat - Adafruit Fork@^2.2.54

[env:default]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
upload_protocol = ${common.upload_protocol}
upload_port = ${common.upload_port}
build_flags =
	${common.build_flags}
	-DAPP_PROFILE=APP_PROFILE_DEFAULT
	-DAPP_STATUS_MODE=STATUS_MODE_AGE
	-DENABLE_GUESS_ITEM_GAME=1
build_unflags = ${common.build_unflags}
lib_deps = ${common.lib_deps}

; 新北兒童節
[env:new_taipei_childrens_day]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
upload_protocol = ${common.upload_protocol}
upload_port = ${common.upload_port}
build_flags =
	${common.build_flags}
	-DAPP_PROFILE=APP_PROFILE_NEW_TAIPEI_CHILDRENS_DAY
	-DAPP_STATUS_MODE=STATUS_MODE_PET_STATE
	-DENABLE_GUESS_ITEM_GAME=0
build_unflags = ${common.build_unflags}
lib_deps = ${common.lib_deps}

[env:small]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
upload_protocol = ${common.upload_protocol}
upload_port = ${common.upload_port}
build_flags =
	${common.build_flags}
	-DAPP_PROFILE=APP_PROFILE_DEFAULT_SMALL
	-DAPP_STATUS_MODE=STATUS_MODE_RANDOM3
	-DENABLE_GUESS_ITEM_GAME=1
build_unflags = ${common.build_unflags}
lib_deps = ${common.lib_deps}

[env:stm32]
extends = env:default
