; Profile Resolver schema version: 1
[platformio]
default_envs = project_18

[env]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
upload_protocol = stlink
upload_port = COM3
build_flags =
	-Os
	-flto
	-ffunction-sections
	-fdata-sections
	-fno-exceptions
build_unflags =
	-Og
	-O0
	-O1
	-O2
	-O3
lib_deps =
	adafruit/Adafruit GFX Library @ ^1.11.5
	adafruit/Adafruit ST7735 and ST7789 Library
	adafruit/SdFat - Adafruit Fork@^2.2.54

[env:profile_base]
build_flags =
	${env.build_flags}
	-DENABLE_DEBUG=0

[env:project_18]
extends = env:profile_base
build_flags =
	${env:profile_base.build_flags}
	-DENABLE_GUESS_GAME=1
	-DENABLE_STARTUP_ANIMATION=1
	-DENABLE_COMMAND_OUTFIT=1
	-DENABLE_COMMAND_SPECIES=1
	-DENABLE_DYNAMIC_ACTION_LAYOUT=1
	-DENABLE_COMMAND_PREDICT=1
	-DENABLE_FIRST_START_ANIMATION=1
	-DENABLE_FIRST_LAUNCH_SELECTION=1
	-DENABLE_OUTFIT_CHOOSE_ANIMATION=1
	-DENABLE_APPEARANCE_SELECTION=1
	-DENABLE_GUESS_GAME_SINGLE_ROUND=0
	-DENABLE_GUESS_GAME_PLAYER_CHOICE_RESULT=1
	-DENABLE_SEQUENTIAL_STATUS_SET_SELECTION=1
	-DAPP_MAX_LOADED_ANIMATIONS=48
	-DAPP_MAX_NAMED_ANIMATIONS=5
	-DAPP_MAX_ANIMATION_VARIANTS=32
	-DAPP_MAX_PET_STATS=8

; Generated by DREAMOLI PET LAB Profile Resolver.
