[platformio]
default_envs = kuromu

[env]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
upload_protocol = stlink
upload_port = COM3
build_flags =
	-Os
	-flto
	-ffunction-sections
	-fdata-sections
	-fno-exceptions
	-DENABLE_RENDER_STATS=0
	-DENABLE_SD_BMP_ASSETS=0
	-DENABLE_SD_RLE_ASSETS=1
	-DENABLE_GUESS_GAME_SINGLE_ROUND=1
build_unflags =
	-Og
	-O0
	-O1
	-O2
	-O3
lib_deps =
	adafruit/Adafruit GFX Library @ ^1.11.5
	adafruit/Adafruit ST7735 and ST7789 Library
	adafruit/SdFat - Adafruit Fork@^2.2.54

[env:default]
build_flags =
	${env.build_flags}
	-DAPP_PROFILE=APP_PROFILE_DEFAULT
	-DAPP_STATUS_MODE=STATUS_MODE_SINGLE_METER
	-DENABLE_GUESS_ITEM_GAME=1

; 新北兒童節
[env:new_taipei_childrens_day]
build_flags =
	${env.build_flags}
	-DAPP_PROFILE=APP_PROFILE_NEW_TAIPEI_CHILDRENS_DAY
	-DAPP_STATUS_MODE=STATUS_MODE_DIRECT
	-DENABLE_GUESS_ITEM_GAME=0
	-DENABLE_STARTUP_ANIMATION=1
	-DENABLE_FIRST_LAUNCH_SELECTION=1
	-DENABLE_OUTFIT_CHOOSE_ANIMATION=1

[env:kuromu]
build_flags =
	${env.build_flags}
	-DAPP_PROFILE=APP_PROFILE_KUROMU
	-DAPP_STATUS_MODE=STATUS_MODE_COMPOSITE_HEALTH
	-DENABLE_GUESS_ITEM_GAME=0
	-DENABLE_OUTFIT_CHOOSE_ANIMATION=1
	-DENABLE_DYNAMIC_ACTION_LAYOUT=1

[env:small_multi_status]
build_flags =
	${env.build_flags}
	-DAPP_PROFILE=APP_PROFILE_DEFAULT_SMALL
	-DAPP_STATUS_MODE=STATUS_MODE_RANDOM_METERS
	-DENABLE_GUESS_ITEM_GAME=1

[env:small_status_anime]
build_flags =
	${env.build_flags}
	-DAPP_PROFILE=APP_PROFILE_DEFAULT_SMALL
	-DAPP_STATUS_MODE=STATUS_MODE_DIRECT
	-DENABLE_GUESS_ITEM_GAME=1

[env:dipsyho]
build_flags =
	${env.build_flags}
	-DAPP_PROFILE=APP_PROFILE_DEFAULT_SMALL
	-DAPP_STATUS_MODE=STATUS_MODE_TRIPLE_METER
	-DENABLE_GUESS_ITEM_GAME=1

[env:small]
build_flags =
	${env.build_flags}
	-DAPP_PROFILE=APP_PROFILE_DEFAULT_SMALL
	-DAPP_STATUS_MODE=STATUS_MODE_SINGLE_METER
	-DENABLE_GUESS_ITEM_GAME=1

[env:small_start]
extends = env:small
build_flags =
	${env:small.build_flags}
	-DENABLE_STARTUP_ANIMATION=1

[env:stm32]
extends = env:default
