#ifndef ACTION_MODES_V11_FIXTURE_H
#define ACTION_MODES_V11_FIXTURE_H

#include <stdint.h>

// Generated by the Web exporter and locked by
// E:\C++\virtualPet\web\tests\pet_editor\test_action_modes_v11_contract.py.
constexpr uint32_t kActionModesV11SchemaFingerprint = 0xE6546C8AUL;
constexpr const char *kActionModesV11Fixture =
    "runtime_contract|3\n"
    "pet_behavior|3|E6546C8A\n"
    "status|1\n"
    "stat|custom0|100|0|100|-2\n"
    "stat|custom1|70|0|100|-2\n"
    "stat|custom2|200|0|300|-3\n"
    "stat|custom3|800|0|1000|-4\n"
    "stat|custom4|100|0|100|-1\n"
    "idle|anim0\n"
    "idle_trigger|trigger0|custom4|<|20|anim5\n"
    "idle_trigger|trigger1|custom0|<|31|anim1\n"
    "idle_trigger|trigger2|custom1|<|31|anim2\n"
    "idle_trigger|trigger3|custom3|<|301|anim4\n"
    "idle_trigger|trigger4|custom2|<|101|anim3\n"
    "action|action0|standard|anim6|1|0\n"
    "action|action1|conditional_animation|anim7|2|0\n"
    "action_condition|action1|10|custom0|<=|25|anim1|1\n"
    "action_condition|action1|20|custom0|>=|75|anim2|2\n"
    "action_condition|action1|30|stage_days|>=|7|anim3|3\n"
    "action_condition|action1|40|custom1|>|50|anim4|4\n"
    "action|action2|random_outcome||0|2\n"
    "action_outcome|action2|outcome0|1|anim8|1\n"
    "action_outcome|action2|outcome1|2|anim9|2\n"
    "action_outcome|action2|outcome2|3|anim10|3\n"
    "action|action3|standard|anim9|1|0\n"
    "action|action4|standard|anim10|1|0\n"
    "action_effect|effect0|action0|change|custom0|40\n"
    "action_effect|effect1|action1|change|custom1|50\n"
    "action_effect|effect2|action3|change|custom2|250\n"
    "action_effect|effect3|action4|change|custom3|500\n"
    "action_outcome_effect|outcome_effect0|action2|outcome0|change|custom4|10\n"
    "action_outcome_effect|outcome_effect1|action2|outcome1|set|custom0|5\n"
    "button|1|user_action|action0\n"
    "button|2|empty|\n"
    "button|3|user_action|action1\n"
    "button|4|user_action|action2\n"
    "button|5|user_action|action3\n"
    "button|6|empty|\n"
    "button|7|user_action|action4\n"
    "button|8|system_command|status\n"
    "status_set|set0|Status\n"
    "crc32|9E98580B\n";

#endif // ACTION_MODES_V11_FIXTURE_H
