#ifndef SLOT_PROJECTION_FIXTURE_H
#define SLOT_PROJECTION_FIXTURE_H

// Generated by the Web runtime-contract exporter from stable identity
// "pet-stat-energy". Runtime records intentionally expose only custom0.
constexpr const char *kSlotProjectionFixture =
    "runtime_contract|1\n"
    "pet_behavior|3|1B1C30C7\n"
    "status|1\n"
    "stat|custom0|100|0|100|-2\n"
    "idle|anim0\n"
    "idle_trigger|trigger0|custom0|<|20|anim5\n"
    "action|action0|anim6|1\n"
    "action_effect|effect0|action0|change|custom0|7\n"
    "guess_effect|guess_effect0|round_correct|set|custom0|88\n"
    "button|1|user_action|action0\n"
    "button|2|empty|\n"
    "button|3|empty|\n"
    "button|4|empty|\n"
    "button|5|empty|\n"
    "button|6|empty|\n"
    "button|7|empty|\n"
    "button|8|system_command|status\n"
    "status_set|set0|Status\n"
    "crc32|A9475DD2\n";

#endif // SLOT_PROJECTION_FIXTURE_H
