#ifndef APP_PROFILE_H
#define APP_PROFILE_H

#define APP_PROFILE_DEFAULT 0
#define APP_PROFILE_VENDOR_A 1
#define APP_PROFILE_VENDOR_B 2

#define STATUS_MODE_AGE 0
#define STATUS_MODE_PET_STATE 1
#define STATUS_MODE_RANDOM3 2

#ifndef APP_PROFILE
#define APP_PROFILE APP_PROFILE_DEFAULT
#endif

#ifndef ENABLE_GUESS_ITEM_GAME
#define ENABLE_GUESS_ITEM_GAME 1
#endif

#ifndef APP_STATUS_MODE
#define APP_STATUS_MODE STATUS_MODE_AGE
#endif

#endif // APP_PROFILE_H
