#ifndef APP_PROFILE_H
#define APP_PROFILE_H

#define APP_PROFILE_DEFAULT 0
#define APP_PROFILE_NEW_TAIPEI_CHILDRENS_DAY 1
#define APP_PROFILE_DEFAULT_SMALL 2

#define STATUS_MODE_AGE 0
#define STATUS_MODE_STATUS 1
#define STATUS_MODE_RANDOM3 2

#define APP_COMMAND_NONE 0
#define APP_COMMAND_FEED_PET 1
#define APP_COMMAND_PREDICT 2
#define APP_COMMAND_GIFT 3
#define APP_COMMAND_MEDICINE 4
#define APP_COMMAND_SHOWER 5
#define APP_COMMAND_HAVE_FUN 6
#define APP_COMMAND_CLEAN 7
#define APP_COMMAND_CHANGE_OUTFIT 8
#define APP_COMMAND_STATUS 9
#define APP_COMMAND_CHANGE_SPECIES 10

#ifndef APP_PROFILE
#define APP_PROFILE APP_PROFILE_DEFAULT
#endif

#ifndef ENABLE_GUESS_ITEM_GAME
#define ENABLE_GUESS_ITEM_GAME 1
#endif

#ifndef ENABLE_STARTUP_ANIMATION
#define ENABLE_STARTUP_ANIMATION 0
#endif

#ifndef ENABLE_FIRST_LAUNCH_SELECTION
#define ENABLE_FIRST_LAUNCH_SELECTION 0
#endif

#ifndef ENABLE_OUTFIT_CHOOSE_ANIMATION
#define ENABLE_OUTFIT_CHOOSE_ANIMATION 0
#endif

#ifndef APP_STATUS_MODE
#define APP_STATUS_MODE STATUS_MODE_AGE
#endif

#ifndef APP_FIRST_LAUNCH_REQUIRED_COMMAND
#define APP_FIRST_LAUNCH_REQUIRED_COMMAND APP_COMMAND_CHANGE_OUTFIT
#endif

#endif // APP_PROFILE_H
