#ifndef APP_PROFILE_H
#define APP_PROFILE_H

#define APP_PROFILE_DEFAULT 0
#define APP_PROFILE_DEFAULT_SMALL 1
#define APP_PROFILE_NEW_TAIPEI_CHILDRENS_DAY 2
#define APP_PROFILE_KUROMU 3
#define APP_PROFILE_DIPSYHO 4

#define STATUS_MODE_DIRECT 0
#define STATUS_MODE_SINGLE_METER 1
#define STATUS_MODE_RANDOM_METERS 2
#define STATUS_MODE_COMPOSITE_HEALTH 3
#define STATUS_MODE_TRIPLE_METER 4

#define STATUS_MODE_STATUS STATUS_MODE_DIRECT
#define STATUS_MODE_AGE STATUS_MODE_SINGLE_METER
#define STATUS_MODE_RANDOM3 STATUS_MODE_RANDOM_METERS
#define STATUS_MODE_COMPOSITE STATUS_MODE_COMPOSITE_HEALTH

#define APP_COMMAND_NONE 0
#define APP_COMMAND_FEED_PET 1
#define APP_COMMAND_PREDICT 2
#define APP_COMMAND_GIFT 3
#define APP_COMMAND_MEDICINE 4
#define APP_COMMAND_SHOWER 5
#define APP_COMMAND_HAVE_FUN 6
#define APP_COMMAND_CLEAN 7
#define APP_COMMAND_CHANGE_OUTFIT 8
#define APP_COMMAND_STATUS 9
#define APP_COMMAND_CHANGE_SPECIES 10

// A generated web profile may override all eight physical menu slots.  Define
// either every APP_COMMAND_SLOT_n macro or none of them so legacy profiles keep
// their existing compile-time layout.
#if defined(APP_COMMAND_SLOT_1) || defined(APP_COMMAND_SLOT_2) || defined(APP_COMMAND_SLOT_3) || defined(APP_COMMAND_SLOT_4) || defined(APP_COMMAND_SLOT_5) || defined(APP_COMMAND_SLOT_6) || defined(APP_COMMAND_SLOT_7) || defined(APP_COMMAND_SLOT_8)
#if !defined(APP_COMMAND_SLOT_1) || !defined(APP_COMMAND_SLOT_2) || !defined(APP_COMMAND_SLOT_3) || !defined(APP_COMMAND_SLOT_4) || !defined(APP_COMMAND_SLOT_5) || !defined(APP_COMMAND_SLOT_6) || !defined(APP_COMMAND_SLOT_7) || !defined(APP_COMMAND_SLOT_8)
#error "Define all APP_COMMAND_SLOT_1..8 values when overriding command slots."
#endif
#define APP_HAS_COMMAND_SLOT_OVERRIDES 1
#else
#define APP_HAS_COMMAND_SLOT_OVERRIDES 0
#endif

#ifndef APP_PROFILE
#define APP_PROFILE APP_PROFILE_DEFAULT
#endif

#ifndef ENABLE_GUESS_ITEM_GAME
#define ENABLE_GUESS_ITEM_GAME 1
#endif

#ifndef ENABLE_STARTUP_ANIMATION
#define ENABLE_STARTUP_ANIMATION 0
#endif

#ifndef ENABLE_FIRST_LAUNCH_SELECTION
#define ENABLE_FIRST_LAUNCH_SELECTION 0
#endif

#ifndef ENABLE_OUTFIT_CHOOSE_ANIMATION
#define ENABLE_OUTFIT_CHOOSE_ANIMATION 0
#endif

#ifndef ENABLE_DYNAMIC_ACTION_LAYOUT
#define ENABLE_DYNAMIC_ACTION_LAYOUT 0
#endif

#ifndef ENABLE_APPEARANCE_SELECTION
#define ENABLE_APPEARANCE_SELECTION 1
#endif

#ifndef ENABLE_COMMAND_PREDICT
#define ENABLE_COMMAND_PREDICT 1
#endif

#ifndef ENABLE_COMMAND_GIFT
#define ENABLE_COMMAND_GIFT 1
#endif

#ifndef ENABLE_COMMAND_OUTFIT
#define ENABLE_COMMAND_OUTFIT 1
#endif

#ifndef ENABLE_COMMAND_SPECIES
#define ENABLE_COMMAND_SPECIES 1
#endif

#ifndef APP_STATUS_MODE
#define APP_STATUS_MODE STATUS_MODE_SINGLE_METER
#endif

#ifndef ENABLE_CUSTOM_RULES
#define ENABLE_CUSTOM_RULES 1
#endif

#ifndef ENABLE_DEBUG
#define ENABLE_DEBUG 0
#endif

#ifndef ENABLE_STATUS_SD_CONFIG
#if APP_STATUS_MODE == STATUS_MODE_SINGLE_METER || APP_STATUS_MODE == STATUS_MODE_RANDOM_METERS || APP_STATUS_MODE == STATUS_MODE_TRIPLE_METER
#define ENABLE_STATUS_SD_CONFIG 1
#else
#define ENABLE_STATUS_SD_CONFIG 0
#endif
#endif

#ifndef ENABLE_STATUS_COMPOSITE
#if APP_STATUS_MODE == STATUS_MODE_COMPOSITE_HEALTH
#define ENABLE_STATUS_COMPOSITE 1
#else
#define ENABLE_STATUS_COMPOSITE 0
#endif
#endif

#ifndef APP_MAX_LOADED_ANIMATIONS
#define APP_MAX_LOADED_ANIMATIONS 48
#endif

#ifndef APP_MAX_NAMED_ANIMATIONS
#define APP_MAX_NAMED_ANIMATIONS 4
#endif

#ifndef APP_MAX_ANIMATION_VARIANTS
#define APP_MAX_ANIMATION_VARIANTS 16
#endif

#ifndef APP_FIRST_LAUNCH_REQUIRED_COMMAND
#define APP_FIRST_LAUNCH_REQUIRED_COMMAND APP_COMMAND_CHANGE_OUTFIT
#endif

#if (ENABLE_COMMAND_OUTFIT || ENABLE_COMMAND_SPECIES || ENABLE_FIRST_LAUNCH_SELECTION) && !ENABLE_APPEARANCE_SELECTION
#error "Appearance selection must be enabled when an appearance command or first-launch selection is enabled."
#endif

#if APP_PROFILE == APP_PROFILE_NEW_TAIPEI_CHILDRENS_DAY
#define APP_INITIAL_SPECIES "pet"
#define APP_INITIAL_OUTFIT "movie"
#elif APP_PROFILE == APP_PROFILE_KUROMU
#define APP_INITIAL_SPECIES "pet"
#define APP_INITIAL_OUTFIT "base"
#elif APP_PROFILE == APP_PROFILE_DIPSYHO
#define APP_INITIAL_SPECIES "andrea"
#define APP_INITIAL_OUTFIT "base"
#else
#define APP_INITIAL_SPECIES "dino"
#define APP_INITIAL_OUTFIT "base"
#endif

#endif // APP_PROFILE_H
